import type { RealOrAiQuestion } from '../questions';

export const realOrAiQuestions: RealOrAiQuestion[] = [
  {
    id: "rai-d1-1",
    type: "real-or-ai",
    xp: 50,
    difficulty: 1,
    imageUrl: "https://picsum.photos/seed/rai-d1-1/800/450",
    correctAnswer: "ai",
    tell: {
      top: 55,
      left: 20,
      width: 30,
      height: 25,
      explanation:
        "[PLACEHOLDER] The hands in this image show six fingers and fused knuckles — a classic sign of AI generation. Current diffusion models consistently fail to render hands with the correct number of fingers.",
    },
    explanation:
      "[PLACEHOLDER] This is an AI-generated image. The clearest tell is the distorted hand anatomy — look for extra fingers, merged joints, or impossible finger lengths.",
  },
  {
    id: "rai-d1-2",
    type: "real-or-ai",
    xp: 50,
    difficulty: 1,
    imageUrl: "https://picsum.photos/seed/rai-d1-2/800/450",
    correctAnswer: "real",
    explanation:
      "[PLACEHOLDER] This is a real photograph. The lighting is consistent, background details are sharp and non-repetitive, and any visible text is legible. When an image lacks the typical AI tells (distorted hands, morphed backgrounds, inconsistent shadows), default to real — over-flagging genuine footage is itself harmful.",
  },
  {
    id: "rai-d1-3",
    type: "real-or-ai",
    xp: 50,
    difficulty: 1,
    imageUrl: "https://picsum.photos/seed/rai-d1-3/800/450",
    correctAnswer: "ai",
    tell: {
      top: 10,
      left: 30,
      width: 40,
      height: 35,
      explanation:
        "[PLACEHOLDER] The crowd in the mid-distance dissolves into a repetitive, textureless pattern with no individual faces — a common AI generation artefact when the model cannot maintain detail at distance.",
    },
    explanation:
      "[PLACEHOLDER] This image was generated by AI. The background crowd loses coherence past a certain depth, merging into a uniform mass. Real crowd photography preserves some individual variation in clothing and posture even at distance.",
  },
  {
    id: "rai-d2-1",
    type: "real-or-ai",
    xp: 60,
    difficulty: 2,
    imageUrl: "https://picsum.photos/seed/rai-d2-1/800/450",
    correctAnswer: "real",
    explanation:
      "[PLACEHOLDER] This is a real photograph. At difficulty 2, real images are selected because they contain details (unusual lighting, wide-angle distortion, compression artefacts) that superficially resemble AI tells. The liar's dividend — the risk that people dismiss genuine evidence as AI — makes over-flagging as dangerous as under-flagging.",
  },
  {
    id: "rai-d2-2",
    type: "real-or-ai",
    xp: 60,
    difficulty: 2,
    imageUrl: "https://picsum.photos/seed/rai-d2-2/800/450",
    correctAnswer: "ai",
    tell: {
      top: 40,
      left: 5,
      width: 45,
      height: 35,
      explanation:
        "[PLACEHOLDER] The text on a sign in the background is partially legible but contains impossible letter sequences — a reliable AI artefact. Real signage in real photographs always contains readable, correctly spelled text.",
    },
    explanation:
      "[PLACEHOLDER] AI-generated images frequently produce garbled, near-legible text on signs, shirts, and labels. If text in an image is almost-but-not-quite readable, this is a strong indicator of AI generation.",
  },
  {
    id: "rai-d2-3",
    type: "real-or-ai",
    xp: 60,
    difficulty: 2,
    imageUrl: "https://picsum.photos/seed/rai-d2-3/800/450",
    correctAnswer: "real",
    explanation:
      "[PLACEHOLDER] This is a real photograph taken under unusual lighting conditions. The colour cast and motion blur may look artificial but are consistent with the camera settings used. Real cameras produce artefacts too — not all imperfections are AI tells.",
  },
  {
    id: "rai-d3-1",
    type: "real-or-ai",
    xp: 80,
    difficulty: 3,
    imageUrl: "https://picsum.photos/seed/rai-d3-1/800/450",
    correctAnswer: "real",
    explanation:
      "[PLACEHOLDER] This is a real photograph. At difficulty 3, real images are specifically selected because they contain features that AI-detection tools frequently misidentify. Over-classifying real images as AI is itself a form of harm (the liar's dividend).",
  },
];
