import type { AiDetectionQuestion } from '@/data/questions';
import { TellReveal } from '@/components/lesson/TellReveal';
import { Button } from '@/components/Button';

interface Props {
  question: AiDetectionQuestion;
  page: number;
  locked: boolean;
  onAnswer: (isCorrect: boolean) => void;
  onPageAdvance: () => void;
}

export function AiDetection({ question, page, locked, onAnswer, onPageAdvance }: Props) {
  if (page === 1) {
    return <TellReveal imageUrl={question.imageUrl} tell={question.tell} onGotIt={onPageAdvance} />;
  }

  return (
    <div className="space-y-5">
      <div className="relative w-full aspect-video rounded-xl overflow-hidden">
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img src={question.imageUrl} alt="" className="w-full h-full object-cover" />
      </div>
      <h2 className="text-text font-bold text-xl text-center">
        Is this image generated by AI?
      </h2>
      <div className="flex gap-3 justify-center">
        <Button variant="yes" disabled={locked} onClick={() => onAnswer(question.correctAnswer === 'yes')}>
          Yes
        </Button>
        <Button variant="no" disabled={locked} onClick={() => onAnswer(question.correctAnswer === 'no')}>
          No
        </Button>
      </div>
    </div>
  );
}
